# Phase 4
Unsupervised ML (Clustering)
Note: This phase requires your general knowledge and thought process to merge the right datasets and the right columns. Collecting quality data is a key factor to create meaningful clusters and Analysis.

Assumption: You were given various crime datasets that contains all the DISTRICTS in each state and you were asked to provide the below data to the higher authorities for further action.

4.1 "Create 3 clusters as below.

Sensitive Area's

Moderate Area's

Peaceful Area's"

4.2 Create DataFrame for each cluster that shows data according to the areas.

4.3 "Analyse your clusters and prepare a report that explains all your observations.

Example -

What is impacting more crimes in sensitive areas.

What needs to be done to reduce crime.

Most safe and unsafe districts.

Etc.......Anything that you observe (If you want, you can plot various graphs to analyze)"

4.4 Capstone project overall story in your own words. Min 1000 words.

# Unsupervised ML (Clustering)
CONSIDERING THE DATABASES THAT CONTAINS THE DISTRICTS !!

In [10]:
district_wise=pd.read_csv("C:\\Users\\admin\\Downloads\\01_District_wise_crimes_committed_IPC_2001_2012.csv")

In [11]:
district_wise

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,...,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
0,ANDHRA PRADESH,ADILABAD,2001,101,60,17,50,0,50,46,...,30,1131,16,149,34,175,0,181,1518,4154
1,ANDHRA PRADESH,ANANTAPUR,2001,151,125,1,23,0,23,53,...,69,1543,7,118,24,154,0,270,754,4125
2,ANDHRA PRADESH,CHITTOOR,2001,101,57,2,27,0,27,59,...,38,2088,14,112,83,186,0,404,1262,5818
3,ANDHRA PRADESH,CUDDAPAH,2001,80,53,1,20,0,20,25,...,23,795,17,126,38,57,0,233,1181,3140
4,ANDHRA PRADESH,EAST GODAVARI,2001,82,67,1,23,0,23,49,...,41,1244,12,109,58,247,0,431,2313,6507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9012,LAKSHADWEEP,LAKSHADWEEP,2012,0,0,0,0,0,0,0,...,3,3,0,1,0,1,0,0,32,60
9013,LAKSHADWEEP,TOTAL,2012,0,0,0,0,0,0,0,...,3,3,0,1,0,1,0,0,32,60
9014,PUDUCHERRY,KARAIKAL,2012,5,6,2,6,0,6,2,...,1,186,0,2,0,1,0,44,392,787
9015,PUDUCHERRY,PUDUCHERRY,2012,24,21,10,7,0,7,17,...,20,632,0,7,2,5,0,219,1668,3494
9016,PUDUCHERRY,TOTAL,2012,29,27,12,13,0,13,19,...,21,818,0,9,2,6,0,263,2060,4281

In [22]:
district_wise=district_wise[['STATE/UT',
 'DISTRICT',
 'MURDER',
 'RAPE',
 'KIDNAPPING & ABDUCTION',
 'DACOITY',
 'ROBBERY',
 'BURGLARY',
 'RIOTS',
 'COUNTERFIETING',
 'ARSON',
 'HURT/GREVIOUS HURT']]

In [13]:
for i in range(len(district_wise['STATE/UT'])):
    if(district_wise['STATE/UT'][i]=='DELHI UT'):
        district_wise['STATE/UT'][i]='DELHI'

C:\Users\admin\AppData\Local\Temp\ipykernel_15704\631657141.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  district_wise['STATE/UT'][i]='DELHI'

In [14]:
district_wise['STATE/UT'].unique()

array(['ANDHRA PRADESH', 'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR',
       'CHHATTISGARH', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH',
       'JAMMU & KASHMIR', 'JHARKHAND', 'KARNATAKA', 'KERALA',
       'MADHYA PRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM',
       'NAGALAND', 'ODISHA', 'PUNJAB', 'RAJASTHAN', 'SIKKIM',
       'TAMIL NADU', 'TRIPURA', 'UTTAR PRADESH', 'UTTARAKHAND',
       'WEST BENGAL', 'A & N ISLANDS', 'CHANDIGARH', 'D & N HAVELI',
       'DAMAN & DIU', 'DELHI', 'LAKSHADWEEP', 'PUDUCHERRY'], dtype=object)

In [15]:
district_wise=district_wise[district_wise['DISTRICT']!='TOTAL']

In [17]:
districtwise_sc=pd.read_csv("C:\\Users\\admin\\Downloads\\01_District_wise_crimes_committed_IPC_2001_2012.csv")

In [18]:
districtwise_sc['STATE/UT'].unique()

array(['ANDHRA PRADESH', 'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR',
       'CHHATTISGARH', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH',
       'JAMMU & KASHMIR', 'JHARKHAND', 'KARNATAKA', 'KERALA',
       'MADHYA PRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM',
       'NAGALAND', 'ODISHA', 'PUNJAB', 'RAJASTHAN', 'SIKKIM',
       'TAMIL NADU', 'TRIPURA', 'UTTAR PRADESH', 'UTTARAKHAND',
       'WEST BENGAL', 'A & N ISLANDS', 'CHANDIGARH', 'D & N HAVELI',
       'DAMAN & DIU', 'DELHI UT', 'LAKSHADWEEP', 'PUDUCHERRY'],
      dtype=object)

In [19]:
districtwise_sc['TOTAL CRIMES AGAINST SC']=districtwise_sc.iloc[:,3:].sum(axis=1)

In [21]:
districtwise_sctot=districtwise_sc[['STATE/UT','DISTRICT','TOTAL CRIMES AGAINST SC']]

In [23]:
districtwise_sctot

            STATE/UT       DISTRICT  TOTAL CRIMES AGAINST SC
0     ANDHRA PRADESH       ADILABAD                     8603
1     ANDHRA PRADESH      ANANTAPUR                     8692
2     ANDHRA PRADESH       CHITTOOR                    12445
3     ANDHRA PRADESH       CUDDAPAH                     6498
4     ANDHRA PRADESH  EAST GODAVARI                    14107
...              ...            ...                      ...
9012     LAKSHADWEEP    LAKSHADWEEP                      127
9013     LAKSHADWEEP          TOTAL                      127
9014      PUDUCHERRY       KARAIKAL                     1663
9015      PUDUCHERRY     PUDUCHERRY                     7589
9016      PUDUCHERRY          TOTAL                     9252

[9017 rows x 3 columns]

In [24]:
districtwise_sctot=districtwise_sctot[districtwise_sctot['DISTRICT']!='TOTAL']

In [26]:
districtwise_st=pd.read_csv("C:\\Users\\admin\\Downloads\\01_District_wise_crimes_committed_IPC_2001_2012.csv")

In [27]:
districtwise_st['STATE/UT'].unique()

array(['ANDHRA PRADESH', 'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR',
       'CHHATTISGARH', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH',
       'JAMMU & KASHMIR', 'JHARKHAND', 'KARNATAKA', 'KERALA',
       'MADHYA PRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM',
       'NAGALAND', 'ODISHA', 'PUNJAB', 'RAJASTHAN', 'SIKKIM',
       'TAMIL NADU', 'TRIPURA', 'UTTAR PRADESH', 'UTTARAKHAND',
       'WEST BENGAL', 'A & N ISLANDS', 'CHANDIGARH', 'D & N HAVELI',
       'DAMAN & DIU', 'DELHI UT', 'LAKSHADWEEP', 'PUDUCHERRY'],
      dtype=object)

In [28]:
districtwise_st=districtwise_st[districtwise_st['DISTRICT']!='TOTAL']

In [29]:
districtwise_st['TOTAL CRIMES AGAINST ST']=districtwise_st.iloc[:,3:].sum(axis=1)

In [51]:
districtwise_sttot=districtwise_st[['STATE/UT','DISTRICT','TOTAL CRIMES AGAINST ST']]

In [52]:
districtwise_sttot

            STATE/UT       DISTRICT  TOTAL CRIMES AGAINST ST
0     ANDHRA PRADESH       ADILABAD                     8603
1     ANDHRA PRADESH      ANANTAPUR                     8692
2     ANDHRA PRADESH       CHITTOOR                    12445
3     ANDHRA PRADESH       CUDDAPAH                     6498
4     ANDHRA PRADESH  EAST GODAVARI                    14107
...              ...            ...                      ...
9010        DELHI UT            STF                       12
9011        DELHI UT           WEST                    14001
9012     LAKSHADWEEP    LAKSHADWEEP                      127
9014      PUDUCHERRY       KARAIKAL                     1663
9015      PUDUCHERRY     PUDUCHERRY                     7589

[8609 rows x 3 columns]

In [36]:
districtwise_child=pd.read_csv("C:\\Users\\admin\\Downloads\\01_District_wise_crimes_committed_IPC_2001_2012.csv")

In [37]:
districtwise_child['STATE/UT'].unique()

array(['ANDHRA PRADESH', 'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR',
       'CHHATTISGARH', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH',
       'JAMMU & KASHMIR', 'JHARKHAND', 'KARNATAKA', 'KERALA',
       'MADHYA PRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM',
       'NAGALAND', 'ODISHA', 'PUNJAB', 'RAJASTHAN', 'SIKKIM',
       'TAMIL NADU', 'TRIPURA', 'UTTAR PRADESH', 'UTTARAKHAND',
       'WEST BENGAL', 'A & N ISLANDS', 'CHANDIGARH', 'D & N HAVELI',
       'DAMAN & DIU', 'DELHI UT', 'LAKSHADWEEP', 'PUDUCHERRY'],
      dtype=object)

In [38]:
districtwise_child=districtwise_child[districtwise_child['DISTRICT']!='TOTAL']

In [39]:
districtwise_child.rename(columns={"Total":"TOTAL CRIMES AGAINST CHILDREN"},inplace=True)

In [40]:
districtwise_child.columns

Index(['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
       'KIDNAPPING AND ABDUCTION OF OTHERS', 'DACOITY',
       'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CRIMINAL BREACH OF TRUST',
       'CHEATING', 'COUNTERFIETING', 'ARSON', 'HURT/GREVIOUS HURT',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES', 'TOTAL IPC CRIMES'],
      dtype='object')

In [42]:
districtwise_childtot=districtwise_child[['STATE/UT','DISTRICT']]

In [43]:
districtwise_childtot

            STATE/UT       DISTRICT
0     ANDHRA PRADESH       ADILABAD
1     ANDHRA PRADESH      ANANTAPUR
2     ANDHRA PRADESH       CHITTOOR
3     ANDHRA PRADESH       CUDDAPAH
4     ANDHRA PRADESH  EAST GODAVARI
...              ...            ...
9010        DELHI UT            STF
9011        DELHI UT           WEST
9012     LAKSHADWEEP    LAKSHADWEEP
9014      PUDUCHERRY       KARAIKAL
9015      PUDUCHERRY     PUDUCHERRY

[8609 rows x 2 columns]

In [44]:
districtwise_women=pd.read_csv("C:\\Users\\admin\\Downloads\\01_District_wise_crimes_committed_IPC_2001_2012.csv")

In [45]:
districtwise_women['STATE/UT'].unique()

array(['ANDHRA PRADESH', 'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR',
       'CHHATTISGARH', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH',
       'JAMMU & KASHMIR', 'JHARKHAND', 'KARNATAKA', 'KERALA',
       'MADHYA PRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM',
       'NAGALAND', 'ODISHA', 'PUNJAB', 'RAJASTHAN', 'SIKKIM',
       'TAMIL NADU', 'TRIPURA', 'UTTAR PRADESH', 'UTTARAKHAND',
       'WEST BENGAL', 'A & N ISLANDS', 'CHANDIGARH', 'D & N HAVELI',
       'DAMAN & DIU', 'DELHI UT', 'LAKSHADWEEP', 'PUDUCHERRY'],
      dtype=object)

In [46]:
districtwise_women=districtwise_women[districtwise_women['DISTRICT']!='TOTAL']

In [47]:
districtwise_women['TOTAL CRIMES AGAINST WOMEN']=districtwise_women.iloc[:,3:].sum(axis=1)

In [50]:
districtwise_womentot=districtwise_women[['STATE/UT','DISTRICT','TOTAL CRIMES AGAINST WOMEN']]

In [53]:
districtwise_womentot

            STATE/UT       DISTRICT  TOTAL CRIMES AGAINST WOMEN
0     ANDHRA PRADESH       ADILABAD                        8603
1     ANDHRA PRADESH      ANANTAPUR                        8692
2     ANDHRA PRADESH       CHITTOOR                       12445
3     ANDHRA PRADESH       CUDDAPAH                        6498
4     ANDHRA PRADESH  EAST GODAVARI                       14107
...              ...            ...                         ...
9010        DELHI UT            STF                          12
9011        DELHI UT           WEST                       14001
9012     LAKSHADWEEP    LAKSHADWEEP                         127
9014      PUDUCHERRY       KARAIKAL                        1663
9015      PUDUCHERRY     PUDUCHERRY                        7589

[8609 rows x 3 columns]

# 4.3.2 What needs to be done to reduce crime.

Reducing crime in India is a complex and multifaceted issue that requires a coordinated trouble from colorful stakeholders, including the government, law enforcement agencies, civil society associations, and the general public. Then are some measures that can help reduce crime in India Strengthen law enforcement The government needs to allocate further coffers and finances to law enforcement agencies to ameliorate their capacity to help and probe crimes. Police reforms should be enforced to make the force more responsible, effective, and effective. Address socio- profitable factors Poverty, severance, and lack of education are significant contributors to crime. The government needs to take measures to address these issues by creating job openings, perfecting access to education, and furnishing introductory amenities like water, electricity, and healthcare. Strengthen the justice system The justice system in India is frequently slow and hamstrung, which can lead to frustration and disillusionment among the public. way should be taken to streamline the justice system and make it more responsive to the requirements of the people. Raise public mindfulness People should be made apprehensive of the consequences of crime and the significance of reporting crime. mindfulness juggernauts should be conducted to educate people about their rights and liabilities. Ameliorate community policing Community policing can help make trust between the police and the community, leading to better crime forestallment and disquisition. The police should work nearly with the community to identify and address original issues. Use technology Technology can play a significant part in precluding and working crimes. The government should invest in contemporizing the police force with advanced technology like CCTV cameras, drones, and digital forensics. Reform the captivity system The captivity system in India is overcrowded and inhuman, which can lead to the farther radicalization of convicts. The government needs to take way to ameliorate the conditions in incarcerations and give convicts with access to education and vocational training.

# 4.3.4 Capstone project overall story in your own words. Min 1000 words.

India is a different country with a population of over1.38 billion people, and crime is a significant issue that affects its citizens. According to the data available from the National Crime Records Bureau( NCRB) for the time 2011, there were a aggregate of2.27 million reported cases of crime in India in 2011, a drop of4.54 from the former time. Crimes against women, including rape, sexual importunity, and domestic violence, continue to be a major concern in India. In 2011, there were reported cases of crimes against women, and11.04 of these cases were related to rape or sexual assault. Despite the enactment of stricter laws and increased public mindfulness, crimes against women remain a patient problem in India. Crimes against children including rape, hijacking and hijacking , murder, traffacking, importation of girl are still the commanding enterprises in India. In 2011, there were 33,049 reported cases of crimes against children, and21.51 of these cases were related to rape or sexual assault, and record46.24 of the csaes are recorded of the murder only among differnt crimes againstchildren.Even after colorful laws and stricter law enforcements being made to control the crimes against children a increase by254.86 can be seen from the time 2001 to 2011. Madhya Pradesh records the utmost cases counting to 40,217 over the times and is followed by Uttar Pradesh and Maharastra counting the figures to 29,969 and 27,845. In the time 2011 33,718 cases were recorded against SC. Involvement of kids can also be seen as a serious trouble to thesociety.Often deceived, mishandled the kids tends towards to conclude the wrong ways. As its easy to impact them stricter laws should be made to overcome thisissue.Total of 23,597 cases were recorded in 2001 which also increased to 27,471 in the time 2011. Madhya Pradesh have the utmost cases recording to 61,939 and manipur being the least in the cases. mortal right violation by the police too offers significant quantum of share in total ipccrimes.Year 2009 have the utmost cases recorded in any time, counting the crimes to 664. There's82.815 drop in the cases from the time 2001 to 2011. Chattisgarh have the utmost cases of mortal right violation across the countries 2001 to 2011. Its also important to note that those who have the duty of maintaining the law and order in the state i, e the police department have also the cases of getting assaulted by theRioutous_mob, crazies, in counter insurrection operation, border opeartions and numerousmore.Uttar pradesh recorded 2150 cases from the time 2001 to 2011, Jammu Kashmir also holds the 4 position with the total count of1142.0. nearly 5 increase in the cases can be seen from the time 2001 to 2011. In JAMMU & KASHMIR a drop in the cases of assaults and payoff of the police/ army labor force acan be seen as the cases in 2001 were 300 which reduced to 50 in 2010,83.33 direct drop in the cases. Maharastra, Uttar Pradesh and Madhya Pradesh had the utmost cases for DACOITY/ thievery/ BURGALARY/ THEFT combined together with counts being in Maharastra-7,17,452 Madhya Pradesh-3,89,927 UTTAR PRADESH-3,66,166. Overall, while there has been a increase in the number of reported crimes in India intimating that there are still significant challenges to be addressed. The government needs to continue its sweats to ameliorate law enforcement, raise public mindfulness, and address socio- profitable factors that contribute to crime.

In addition to this, the government also needs to address the issue of corruption within the police force. This is rampant in many parts of India and officers are not held accountable for their actions. This leads to a lack of trust in the police and leads to more people taking matters into their own hands instead of relying on the police for protection. There is also a need to provide better training for police officers. This can help them to better understand their roles and responsibilities and to be prepared for different types of situations. This can also help them to be more effective in their work and to serve the public better. Furthermore, there should be an officer so that they can handle difficult situations with sensitivity and understanding. Finally, more resources need to be allocated towards increasing public awareness around crime prevention, as this is key in helping reduce crime rates.

Overall, it is clear that there are still many challenges facing India when it comes to crime. The government needs to continue its efforts to improve law enforcement, raise public awareness, and address the socio-economic factors that contribute to crime. In addition, there needs to be more focus on reducing corruption within the police force and providing better training for officers. Furthermore, resources should be allocated towards increasing public awareness around crime prevention to reduce crime rates. With these steps in place, India can start to make progress toward reducing crime and improving safety for its citizens.